version: '3.8'

services:
  flutter-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    command: ["sleep", "infinity"]
